# Generated by Django 5.1.7 on 2025-03-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catogaory',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('sports', 'Sports'), ('Gaming', 'Gaming')], max_length=200),
        ),
    ]
