# Generated by Django 5.1.7 on 2025-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_product_catogaory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=2000)),
                ('email', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=3000)),
                ('city', models.CharField(max_length=2000)),
                ('state', models.CharField(max_length=2000)),
                ('zip_code', models.CharField(max_length=200)),
            ],
        ),
    ]
