# Generated by Django 5.1.7 on 2025-03-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
